### ISSUE TITLE
Extension not working with the redesign

### ISSUE THREAD

**Issue by petko10** [strasse86/Reddit-User-Explorer#1]
I don't know what info would be useful, but the extension does not show the bar charts as expected, and rather just opens the user info page.

**Comment by strasse86** [comment]
Thank you for the feedback.  Have you pressed and keep pressed Ctrl+ left mouse  click on the username  ? I have just tried it with the new redesign and it works for me. If the click is registered you should see that the extension is working as the extension icon is flashing. Also you need to wait a bit as the information is gathered live

**Comment by petko10** [comment]
Ok, I guess I just experienced a delay or didn't refresh the page after installing the extension or something like that. Now it works. Thanks for answering
